config/routes.rb
Rails.application.routes.draw do

  get "/pokemons/search", to: "pokemons#search"
  get "/pokemons/all", to: "pokemons#all"
  #must be after search
  resources :pokemons, except: [:new]
  get "/pokemons/pokedex/:id", to: "pokemons#pokedex"
  get "/pokemons_alternate", to: "pokemons#index_alternate"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    @pokemon = Pokemon.find(params[:id])
    render json: @pokemon
  end

  def pokedex
    render json: Pokemon.where(pokedex_id: params[:id]).to_a
  end

  def search
    puts "SEEEEEARCCCH SEARCH"
    render json: Pokemon.where(filtered_params).to_a
  end

  def index #with pagy
    @pagination_mode = "pagy"
    @pagy, @pokemons = pagy((Pokemon.all), items: 20)
  end

  def index_alternate #to show an alternate paging (all datatable, all preloaded)
    @pagination_mode = "datatable"
    poke_all = Pokemon.all
    @pagy, @pokemons = pagy((poke_all), items: poke_all.count)
  end

  def all
    @pokemons = Pokemon.all
    render json: @pokemons
  end

  #no "new" because no UI
  def create
    @pokemon = Pokemon.create(filtered_params)
    head :created
  end

  #set values with specific id in table
  def update
    @pokemon = Pokemon.find(params[:id])
    @pokemon.update!(filtered_params)
    head :no_content
  end

  def destroy
    Pokemon.find(params[:id]).destroy!
    head :no_content
  end

  private def filtered_params
    params.permit(*Pokemon.column_names)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/pokemons_helper.rb
require 'csv'

module PokemonsHelper
  def import_pokemon(filename)
    start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    ActiveRecord::Base.transaction do
      #Note: if file was much bigger reading file & using foreach may be more appropriate to save memory
      # For 800 records, ~0.38 sec with foreach, vs bulk ~0.11 sec
      data = CSV.parse(File.read(filename), headers: true)
      data_to_insert = data.map { |line|
        {
          pokedex_id: line["#"],
          name: line["Name"],
          type1: line["Type 1"],
          type2: line["Type 2"],
          total: line["Total"],
          hp: line["HP"],
          attack: line["Attack"],
          defense: line["Defense"],
          sp_atk: line["Sp. Atk"],
          sp_def: line["Sp. Def"],
          speed: line["Speed"],
          generation: line["Generation"],
          legendary: line["Legendary"]
        }
      }
      Pokemon.insert_all(data_to_insert)
      puts "Created #{data.count} pokemons to database"
    end

    end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    puts "Transaction took #{end_time - start_time} seconds"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApplicationNotApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "jquery-3.7.0.min" %>
    <%= stylesheet_link_tag "jquery.dataTables_1.13.5.min.css" %>
    <%= javascript_include_tag "jquery.dataTables_1.13.5.min.js" %>
    <%= stylesheet_link_tag "bootstrap.min" %>
    <%= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "pokemon_table_init" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>Only one page loaded at a time, pagination with xhr
  <%=link_to "An alternative", pokemons_alternate_path %>
</h1>
<div class="pag-bar mt-1 pt-1">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
<table id="myTable" class="display" pagination_type="<%= @pagination_mode%>" page_size="<%= @page_size %>"
       pagy_items="<%= @pagy.items %>">
  <thead>
  <tr>
    <% Pokemon.column_names.each do |col| %>
    <th><%= col.to_s %></th>
    <% end %>
    <th>
      Actions
    </th>
  </tr>
  </thead>
  <tbody>
  <% @pokemons.each do |poke| %>
  <tr>
      <% Pokemon.column_names.each do |col| %>
      <td><%= poke.attributes[col] %></td>
      <% end %>
      <td><a href="#" class="delete">DELETE</a></td>
  </tr>
  <% end %>
  </tbody>
</table>
<div class="pag-bar mt-1 pt-1">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/pokemons/index_alternate.html.erb
<h1>All pokemons preloaded, pagination without xhr, w/ datatable
  <%=link_to "An alternative", pokemons_path %>
</h1>
<table id="myTable" class="display" pagination_type="<%= @pagination_mode%>">
  <thead>
  <tr>
    <% Pokemon.column_names.each do |col| %>
      <th><%= col.to_s %></th>
    <% end %>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @pokemons.each do |poke| %>
    <tr>
      <% Pokemon.column_names.each do |col| %>
        <td><%= poke.attributes[col] %></td>
      <% end %>
      <td><a href="#" class="delete">DELETE</a></td>
    </tr>
  <% end %>
  </tbody>
</table>